# NUMPY

In [1]:
import numpy as np

In [2]:
l =[1,2,3,4]

In [3]:
ar = np.array(l)

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
a = [2,3,4]

In [9]:
np.asanyarray(a)

array([2, 3, 4])

In [10]:
b = np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4]])

In [12]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [13]:
a = np.array(l)

In [14]:
c=a

In [15]:
c

array([1, 2, 3, 4])

In [16]:
a

array([1, 2, 3, 4])

In [17]:
c[0]=100

In [18]:
c

array([100,   2,   3,   4])

In [19]:
# there will be change in a also 
a

array([100,   2,   3,   4])

In [20]:
d = np.copy(a)

In [21]:
d

array([100,   2,   3,   4])

In [22]:
a

array([100,   2,   3,   4])

In [23]:
a[1]=400


In [24]:
a

array([100, 400,   3,   4])

In [25]:
# there will be no change in d
d

array([100,   2,   3,   4])

In [26]:
np.fromfunction(lambda i , j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i , j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
iterable = (i*i for i in range(5))

In [29]:
np.fromiter(iterable , float )

array([ 0.,  1.,  4.,  9., 16.])

In [30]:
# sep - separater 
np.fromstring('234 234', sep= ' ' )

array([234., 234.])

In [31]:
np.fromstring('4,5', sep= ',' )

array([4., 5.])

In [32]:
t = [2,3,4,5,6]

In [33]:
ar = np.array(t)

In [34]:
ar

array([2, 3, 4, 5, 6])

In [35]:
ar.ndim

1

In [36]:
ar2 = np.array([[1,2,3,4],[2,3,4,5]])
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [37]:
ar2.ndim

2

In [38]:
# no of elements 
ar.size

5

In [39]:
ar2.size

8

In [40]:
ar.shape

(5,)

In [41]:
# 2 rows , 4 columns 
ar2.shape

(2, 4)

In [42]:
ar.dtype

dtype('int64')

In [43]:
ar2.dtype

dtype('int64')

In [44]:
ar22 = np.array([(1.4,45,45), (23,45,66)])
ar22


array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [45]:
ar22.dtype

dtype('float64')

In [46]:
# it does not take floating value 
list(range(5))

[0, 1, 2, 3, 4]

In [47]:
np.arange(2.3, 5.6 , .3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [48]:
list(np.arange(2.3, 5.6 , .3))

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [49]:
# 1 to 5 line - generate 10 data 
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [50]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [51]:
on = np.ones((2,3,2))
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [52]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [53]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [54]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [55]:
np.logspace(2,5,10 , base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [56]:
arr3 = np.random.randn(3,4)

In [57]:
arr3

array([[ 0.87532357,  0.26829493, -0.44826586,  0.36975521],
       [ 0.21479921, -0.42760979, -1.74928305,  0.9117617 ],
       [ 0.79231825,  2.55471348,  1.42987294,  1.4978736 ]])

In [58]:
import pandas as pd 

In [59]:
pd.DataFrame(arr3)

0         1         2         3
0  0.875324  0.268295 -0.448266  0.369755
1  0.214799 -0.427610 -1.749283  0.911762
2  0.792318  2.554713  1.429873  1.497874

In [60]:
s = np.random.randint(1,110 , (3,4))
s

array([[13, 77, 27,  5],
       [93, 37, 31, 30],
       [80, 69, 62, 29]])

In [61]:
pd.DataFrame(s)

0   1   2   3
0  13  77  27   5
1  93  37  31  30
2  80  69  62  29

In [62]:
# to convert into csv file 
# pd.DataFrame(s).to_csv('test.csv')

In [63]:
arr4 = np.random.randint(1,3 , (3,3))
arr5 = np.random.randint(1,3 , (3,3))

In [64]:
arr4

array([[1, 1, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [65]:
arr5

array([[2, 2, 1],
       [1, 2, 2],
       [2, 2, 2]])

In [66]:
arr4+arr5

array([[3, 3, 2],
       [2, 4, 3],
       [4, 4, 3]])

In [67]:
arr4- arr5

array([[-1, -1,  0],
       [ 0,  0, -1],
       [ 0,  0, -1]])

In [68]:
# index -wise multiplication 
arr4 * arr5

array([[2, 2, 1],
       [1, 4, 2],
       [4, 4, 2]])

In [69]:
# marix multiplication 
arr4 @ arr5

array([[ 5,  6,  5],
       [ 6,  8,  7],
       [ 8, 10,  8]])

In [70]:
arr4/0

/tmp/ipykernel_8901/1674986024.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [71]:
arr4 +100

array([[101, 101, 101],
       [101, 102, 101],
       [102, 102, 101]])

In [72]:
#  Broadcasting

In [73]:
# linaer array 
arr6 = np.zeros((4,4))
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
# array
row = np.array([1,2,3,4])
row

array([1, 2, 3, 4])

In [75]:
row.shape  

(4,)

In [76]:
# it is doing row wise addition - row-wise broadcating 
arr6 + row 

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [77]:
 row.T

array([1, 2, 3, 4])

In [78]:
col = np.array([[1,2,3,4]])
col

array([[1, 2, 3, 4]])

In [79]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [80]:
# column  wise broadcasting
col.T + arr6

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [81]:
arr7 = np.random.randint(1,4 ,(3,4))
arr7

array([[1, 2, 2, 1],
       [2, 1, 2, 1],
       [2, 1, 2, 3]])

In [82]:
np.sqrt(arr7)

array([[1.        , 1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.41421356, 1.73205081]])

In [83]:
np.exp(arr7)

array([[ 2.71828183,  7.3890561 ,  7.3890561 ,  2.71828183],
       [ 7.3890561 ,  2.71828183,  7.3890561 ,  2.71828183],
       [ 7.3890561 ,  2.71828183,  7.3890561 , 20.08553692]])

In [84]:
np.log10(arr7)

array([[0.        , 0.30103   , 0.30103   , 0.        ],
       [0.30103   , 0.        , 0.30103   , 0.        ],
       [0.30103   , 0.        , 0.30103   , 0.47712125]])

In [85]:
# array manipulation 

In [86]:
arr8 = np.random.randint(1,10, (3,4))
arr8

array([[5, 3, 9, 3],
       [1, 3, 6, 1],
       [3, 5, 9, 6]])

In [87]:
arr8.reshape(6,2)

array([[5, 3],
       [9, 3],
       [1, 3],
       [6, 1],
       [3, 5],
       [9, 6]])

In [88]:
#  to do in single dimension
arr8.flatten()

array([5, 3, 9, 3, 1, 3, 6, 1, 3, 5, 9, 6])

In [89]:
arr9 = np.array([1,2,3,4])
arr9


array([1, 2, 3, 4])

In [90]:
arr9.ndim

1

In [91]:
# expanding along column 
z = np.expand_dims(arr9 , axis =1 )
z

array([[1],
       [2],
       [3],
       [4]])

In [92]:
# expanding along column 

y = np.expand_dims(arr9 , axis =0 )
y

array([[1, 2, 3, 4]])

In [93]:
z.ndim

2

In [94]:
y.ndim

2

In [95]:
arr8

array([[5, 3, 9, 3],
       [1, 3, 6, 1],
       [3, 5, 9, 6]])

In [96]:
np.squeeze(arr8)

array([[5, 3, 9, 3],
       [1, 3, 6, 1],
       [3, 5, 9, 6]])

In [97]:
data = np.array([[1],[2],[3]])

In [98]:
data

array([[1],
       [2],
       [3]])

In [99]:

np.squeeze(data)

array([1, 2, 3])

In [100]:
np.repeat(arr9 , 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [101]:
# for shifting 
np.roll(arr9 , 2)

array([3, 4, 1, 2])

In [102]:
arr9

array([1, 2, 3, 4])

In [103]:
np.diag(arr9)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [104]:
~arr9

array([-2, -3, -4, -5])

In [105]:
arr10 = np.array(["cat ", "dog"])
arr10

array(['cat ', 'dog'], dtype='<U4')

In [106]:
np.char.upper(arr10)

array(['CAT ', 'DOG'], dtype='<U4')

In [107]:
np.char.title(arr10)

array(['Cat ', 'Dog'], dtype='<U4')

In [108]:
np.char.capitalize(arr10)

array(['Cat ', 'Dog'], dtype='<U4')

In [109]:
arr8

array([[5, 3, 9, 3],
       [1, 3, 6, 1],
       [3, 5, 9, 6]])

In [110]:
np.sin(arr8)

array([[-0.95892427,  0.14112001,  0.41211849,  0.14112001],
       [ 0.84147098,  0.14112001, -0.2794155 ,  0.84147098],
       [ 0.14112001, -0.95892427,  0.41211849, -0.2794155 ]])

In [111]:
np.tan(arr8)

array([[-3.38051501, -0.14254654, -0.45231566, -0.14254654],
       [ 1.55740772, -0.14254654, -0.29100619,  1.55740772],
       [-0.14254654, -3.38051501, -0.45231566, -0.29100619]])

In [112]:
np.power(arr8 ,2)

array([[25,  9, 81,  9],
       [ 1,  9, 36,  1],
       [ 9, 25, 81, 36]])