In [1]:
import numpy as np

Numpy Array

In [2]:
# create 1D array

arr_1 = np.array([2,5,7,23,87])
arr_1

array([ 2,  5,  7, 23, 87])

In [3]:
# create 2D array 

arr_2 = np.array([[2,4,5,5] , [5,8,9,0]])
arr_2


array([[2, 4, 5, 5],
       [5, 8, 9, 0]])

In [4]:
# to check type and shape 

t = type(arr_2)
print("type",t)

s = arr_2.shape  #show dimension of array 
print("shape",s)


type <class 'numpy.ndarray'>
shape (2, 4)


In [5]:
#  Squaring Elements

numpy_squares = arr_1 ** 2
numpy_squares

array([   4,   25,   49,  529, 7569])

In [6]:
#  array of zeros(2x3)
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# array of ones(4x3)
b = np.ones((4,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
# for shape 
b.shape

(4, 3)

In [8]:
# array filled with any number(for eg 6)
c = np.full((3,4),6)
c

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [9]:
#  identity matrix
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
# like range from 1 to 10 
d = np.arange(1, 10, 3)
d

array([1, 4, 7])

In [11]:
# evenly spaced
e = np.linspace(0,10,5)
e

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Characteristics of array 

In [12]:
# to check characteristics of array 

arr = np.array([[20,40,50],[22,66,88]])

print("shape:", arr.shape)
print("size:", arr.size)
print("datatype:", arr.dtype)    #all elements share the same datatype 
print("dimension:", arr.ndim)

shape: (2, 3)
size: 6
datatype: int64
dimension: 2


In [13]:
#  changing data type 

f = np.array([1,2,3] , dtype = np.float32)
print(f.dtype)

float32


In [14]:
f_int = f.astype(np.int32)

In [15]:
f_int

array([1, 2, 3], dtype=int32)

In [16]:
# reshapping 

g = np.array([[[1,2,3], [5,6,8]]])
print(g)

[[[1 2 3]
  [5 6 8]]]


In [17]:
reshaped_g = g.reshape((3,2))

In [18]:
reshaped_g

array([[1, 2],
       [3, 5],
       [6, 8]])

In [54]:
# flatting (2D --> 1D) (multidimensional to single dimension )

flatted_g = g.flatten()
print(flatted_g)

[1 2 3 5 6 8]


Indexing and slicing

In [20]:
# indexing 

h = np.array([23,63,75,12,89,20,40])
h[0]

np.int64(23)

In [21]:
h[-1]

np.int64(40)

In [22]:
# slicing   --- changes in slice effect the original array because they share same data in memory  
h[1:4]

array([63, 75, 12])

In [23]:
h[::2]   # with gap of 2  

array([23, 75, 89, 40])

In [24]:
# select multiple items (fancing indexing)
i = np.array([10,50,20,30,40,60,90,25,75])

idx = [0,2,7]

i[idx]


array([10, 20, 25])

In [25]:
# boolean masking

mask = i > 40 

i[mask]

array([50, 60, 90, 75])

In [26]:
# 3-D array 

j = np.array([[1,2,3],[4,5,6],[7,8,9]])
j

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
# sum along axis 
# Axis 0 = rows (vertical movement), Axis 1 = columns (horizontal movement)

k = np.sum(j , axis= 0 )   # along rows 
l = np.sum(j , axis = 1)    # along columns

k , l

(array([12, 15, 18]), array([ 6, 15, 24]))

In [29]:
# accessing element 
print(j[2,2])

9


In [32]:
# slicing
print(j[0:2 , 0:1])
print(j[0:2, 1:3])

[[1]
 [4]]
[[2 3]
 [5 6]]


In [35]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
#  it's shape - (depth, rows , columns)
arr3D.shape 

(2, 2, 3)

In [44]:
# First sheet, second row, third column - accessing 
print(arr3D[0, 1, 2]) 

6


In [45]:
# to get the first row from both sheets
print(arr3D[:, 0, :])

[[1 2 3]
 [7 8 9]]


In [52]:
# to get all rows of the first column
s = np.array([[2,4,5],[7,2,1],[9,0,4]])
print(s)
first_col = s[:, 0]
print(first_col)

[[2 4 5]
 [7 2 1]
 [9 0 4]]
[2 7 9]


In [51]:
# to get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


Data types in numpy

NumPy arrays are homogeneous, meaning all elements must be of the same type.     
int32 , int64 : Integer         
float32 , float64 : Floating-point             
complex64 , complex128 : Complex number 

In [55]:
# to find datatype 
r = np.array([2,6,5,3])
print(r.dtype)


int64


In [56]:
# for changing Data Types
t = np.array([2.4,7.6,3.9,4.1])
print(t)
print(t.shape)

[2.4 7.6 3.9 4.1]
(4,)


In [59]:
t_int = t.astype(np.int64)
print(t_int)
print(t_int.shape)

[2 7 3 4]
(4,)


In [60]:
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)
arr_small = arr_large.astype(np.int32) # Downcasting to a smaller dtype

In [ ]:
print(arr_small)
arr_large.dtype , arr_small.dtype

[1000000 2000000 3000000]


(dtype('int64'), dtype('int32'))

In [64]:
# memory usage 
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

# Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int64.nbytes)

# Output: 12 bytes (3 elements * 4 bytes each)
print(arr_int32.nbytes) 

24
12


In [66]:
# string data type 
z = np.array(['hey', 'hii', 'hello'])
print(z)

['hey' 'hii' 'hello']


In [67]:
z.dtype

dtype('<U5')

In [70]:
# Unicode string array
# U10 - here 10 specifies max length of string
y = np.array(['cow', 'dog', 'cat'], dtype='U10') 
print(y)

['cow' 'dog' 'cat']


In [71]:
y.dtype

dtype('<U10')

In [72]:
#  Complex Numbers 

x = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(x)

[1.+2.j 3.+4.j 5.+6.j]


In [73]:
x.dtype

dtype('complex128')

In [77]:
# Object Data Type
# to store mixed or complex data types (eg: Python objects)

w = np.array([{'a': 1}, [7,4,3], 'Hii'], dtype=object)
print(w)

[{'a': 1} list([7, 4, 3]) 'Hii']


Built in mathematical functions in numpy 

In [78]:
v = np.array([10, 20, 30, 40, 50])


In [79]:
# for mean - average
np.mean(v)

np.float64(30.0)

In [82]:
# for Standard deviation
u = np.std(v)
print(u)

14.142135623730951


In [83]:
# for Variance
np.var(v)

np.float64(200.0)

In [87]:
# for  Maximum value
print(np.max(v))

# for Index of maximum value
print(np.argmax(v))

# for  Sum of elements
print(np.sum(v))

# for Product of elements
print(np.prod(v))

# for log 
print(np.log(v))

# for cumulative sum
print(np.cumsum(v))

50
4
150
12000000
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
[ 10  30  60 100 150]
