In [1]:
import numpy as np

In [2]:
# create 1D array

arr_1 = np.array([2,5,7,23,87])
arr_1

array([ 2,  5,  7, 23, 87])

In [3]:
# create 2D array 

arr_2 = np.array([[2,4,5,5] , [5,8,9,0]])
arr_2


array([[2, 4, 5, 5],
       [5, 8, 9, 0]])

In [4]:
# to check type and shape 

t = type(arr_2)
print("type",t)

s = arr_2.shape  #show dimension of array 
print("shape",s)


type <class 'numpy.ndarray'>
shape (2, 4)


In [5]:
#  Squaring Elements

numpy_squares = arr_1 ** 2
numpy_squares

array([   4,   25,   49,  529, 7569])

In [6]:
#  array of zeros(2x3)
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# array of ones(4x3)
b = np.ones((4,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# array filled with any number(for eg 6)
c = np.full((3,4),6)
c

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [9]:
#  identity matrix
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
# like range from 1 to 10 
d = np.arange(1, 10, 3)
d

array([1, 4, 7])

In [11]:
# evenly spaced
e = np.linspace(0,10,5)
e

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
# to check characteristics of array 

arr = np.array([[20,40,50],[22,66,88]])

print("shape:", arr.shape)
print("size:", arr.size)
print("datatype:", arr.dtype)    #all elements share the same datatype 
print("dimension:", arr.ndim)

shape: (2, 3)
size: 6
datatype: int64
dimension: 2


In [13]:
#  changing data type 

f = np.array([1,2,3] , dtype = np.float32)
print(f.dtype)

float32


In [14]:
f_int = f.astype(np.int32)

In [15]:
f_int

array([1, 2, 3], dtype=int32)

In [16]:
# reshapping 

g = np.array([[[1,2,3], [5,6,8]]])
print(g)

[[[1 2 3]
  [5 6 8]]]


In [17]:
reshaped_g = g.reshape((3,2))

In [18]:
reshaped_g

array([[1, 2],
       [3, 5],
       [6, 8]])

In [19]:
# flatting (2D --> 1D) 

flatted_g = g.flatten()
print(flatted_g)

[1 2 3 5 6 8]


In [20]:
# indexing 

h = np.array([23,63,75,12,89,20,40])
h[0]

np.int64(23)

In [21]:
h[-1]

np.int64(40)

In [22]:
# slicing   --- changes in slice effect the original array because they share same data in memory  
h[1:4]

array([63, 75, 12])

In [23]:
h[::2]   # with gap of 2  

array([23, 75, 89, 40])

In [24]:
# select multiple items (fancing indexing)
i = np.array([10,50,20,30,40,60,90,25,75])

idx = [0,2,7]

i[idx]


array([10, 20, 25])

In [25]:
# boolean masking

mask = i > 40 

i[mask]

array([50, 60, 90, 75])